import Image from 'next/image';
import Link from 'next/link';
import EventPlanner from '../../components/EventPlanner';
import PropertyGallery from '../../components/PropertyGallery';
import Icon from '../../components/Icon';
import {properties} from '../../lib/properties';
import s from './page.module.css';
export const metadata={title:'Weddings & Events in Agra & Vrindavan | SNJ Group',description:'Explore SNJ celebration venues in Agra and Vrindavan. Plan your wedding, engagement, birthday or Bhagwat Katha.'};
const occasions=['Wedding','Engagement','Birthday','Bhagwat Katha'];
export default async function Page({searchParams}:{searchParams:Promise<{occasion?:string;venue?:string}>}){
 const query=await searchParams;const selected=occasions.includes(query.occasion||'')?query.occasion!:'Wedding';const venue=properties.find(p=>p.slug===query.venue);
 return <main id="main-content" tabIndex={-1} className={s.page}><section className={s.hero}><Image src="/images/wedding-table.jpg" alt="Celebration table inspiration" fill sizes="100vw" priority/><div className={s.shade}/><div className={s.heroCopy}><p>AGRA &middot; VRINDAVAN</p><h1>Weddings & celebrations</h1><span>A place for everyone. A moment to remember.</span><a href="#event-enquiry">Plan your event <Icon name="arrow"/></a></div></section>
 <div className={s.wrap}><nav className={s.occasions} aria-label="Choose your occasion">{occasions.map((o,i)=><Link key={o} href={'/weddings-events?occasion='+encodeURIComponent(o)+(venue?'&venue='+venue.slug:'')+'#venues'} aria-current={o===selected?'true':undefined}><Icon name={i===0?'diamond':i===3?'temple':i===1?'sparkle':'calendar'}/>{o}<Icon name="arrow"/></Link>)}</nav>
 <section id="venues" className={s.section}><div className={s.sectionTitle}><div><p>OUR VENUES</p><h2>Find your setting.</h2></div><span>4 properties &middot; 2 destinations</span></div><div className={s.venues}>{properties.map((p,i)=><article className={s.card} key={p.slug}><div className={s.cardTop}><span>{p.city}</span><Icon name={p.hotel?'banquet':'garden'}/></div><h3>{p.name}</h3><p>{p.description}</p><div className={s.features}>{p.features.filter(f=>f!=='Hotel stays').slice(0,3).map(f=><span key={f}>{f}</span>)}</div><div className={s.capacity}><Icon name="user"/><span>Capacity & packages on request</span></div><div className={s.cardLinks}><Link href={'/weddings-events?occasion='+encodeURIComponent(selected)+'&venue='+p.slug+'#event-enquiry'}>Choose venue <Icon name="arrow"/></Link><Link href={'/properties/'+p.slug}>View property</Link></div></article>)}</div></section>
 <section className={s.section}><div className={s.sectionTitle}><h2>Celebration inspiration</h2></div><PropertyGallery hotel={false} photos={[['wedding-table.jpg','Celebrations']]}/></section><section className={s.arrangements}><div><p>YOUR CELEBRATION</p><h2>Plan the details that matter.</h2></div><div className={s.arrangementGrid}>{[['banquet','Venue & seating','Indoor or outdoor preferences'],['restaurant','Dining','Menu and catering requirements'],['sparkle','Decor','Theme, flowers and arrangements'],['bed','Guest stays','Rooms for family and guests']].map(([icon,title,text])=><div key={title}><Icon name={icon as 'banquet'|'restaurant'|'sparkle'|'bed'}/><strong>{title}</strong><span>{text}</span></div>)}</div></section>
 <section id="event-enquiry" className={s.enquiry}><div className={s.sectionTitle}><div><p>LET’S PLAN</p><h2>Your event details</h2></div><span>{selected}{venue?' / '+venue.name:''}</span></div><EventPlanner key={selected+(venue?.slug||'')} initialOccasion={selected} initialVenue={venue?.name}/></section>
 <section className={s.faq}><h2>Before you plan</h2>{[['Can I arrange rooms for my guests?','Add your room requirements to the enquiry. Accommodation and venue availability need confirmation.'],['What is included in an event package?','Catering, decoration, seating and other inclusions are agreed with the property for your event.'],['Does this enquiry reserve a date?','No. The planner prepares a draft to download or copy. A booking requires confirmation from the property.']].map(([q,a])=><details key={q}><summary>{q}<Icon name="chevron"/></summary><p>{a}</p></details>)}</section></div><a className={s.mobileCta} href="#event-enquiry">Plan your event <Icon name="arrow"/></a></main>;
}
