'use client';
import { useState } from 'react';
import Link from 'next/link';
import Icon from './Icon';
export type GuestView = 'bookings' | 'login' | 'offers';
type Props = { initial: GuestView; profile?: boolean };
export default function GuestServices({initial,profile=false}:Props){
 const view=initial; const [city,setCity]=useState('All destinations'); const accountTab=profile?'profile':'login';
 const titles={bookings:'Your stays, all in one place.',login:accountTab==='profile'?'A stay that feels like you.':'Welcome to SNJ.',offers:'A little more to look forward to.'};
 return <section className="guest-page-card">
 <div className="guest-body"><p className="eyebrow">{view==='offers'?'OFFERS & PACKAGES':view==='bookings'?'YOUR TRAVEL COMPANION':'YOUR SNJ ACCOUNT'}</p><h1 id="guest-title">{titles[view]}</h1>
 {view==='login' && <><p className="guest-lead">One account for your stays, celebrations and travel details.</p><div className="account-switch" role="group" aria-label="Account view"><Link href="/login" aria-current={!profile?'page':undefined}>Login</Link><Link href="/profile" aria-current={profile?'page':undefined}>Profile</Link></div>
 {accountTab==='login'?<div className="login-preview"><label htmlFor="guest-email">Email address</label><input id="guest-email" type="email" autoComplete="email" disabled placeholder="you@example.com" aria-describedby="login-status" /><button className="guest-primary" disabled><Icon name="lock" /> Login available at launch</button><p id="login-status" className="guest-notice">Online accounts are not available yet. Sign-in will open when online reservations launch.</p></div>:<div className="profile-preview"><span className="guest-avatar"><Icon name="user" /></span><h3>Your personal space</h3><p>Sign in when accounts launch to manage your personal details and see your booking history.</p><div className="profile-feature"><Icon name="user" /><span>Personal details<small>Name and contact information</small></span><Icon name="lock" /></div><div className="profile-feature"><Icon name="suitcase" /><span>Booking history<small>Your stays and reservation details</small></span><Icon name="lock" /></div></div>}</>}
 {view==='bookings' && <><p className="guest-lead">A home for your upcoming stays and past memories.</p><div className="booking-access"><span className="guest-avatar"><Icon name="suitcase" /></span><h3>Booking lookup opens at launch</h3><p>Online booking history is not connected yet. Existing reservations cannot be checked here.</p><Link className="guest-primary" href="/login"><Icon name="user" /> Login / Profile <Icon name="arrow" /></Link></div><details className="booking-help"><summary>Already booked with a property?<Icon name="chevron" /></summary><p>Use the phone number or email on your booking confirmation. For a booking made on another travel website, use that provider's booking page.</p></details><details className="booking-help"><summary>Need to change or cancel a stay?<Icon name="chevron" /></summary><p>Contact the property or the provider that confirmed your booking. Changes and refunds depend on your reservation's terms.</p></details></>}
 {view==='offers' && <><p className="guest-lead">Discover published offers for your next SNJ stay.</p><div className="offer-filters" role="group" aria-label="Offer destination">{['All destinations','Agra','Vrindavan'].map(c=><button key={c} aria-pressed={city===c} onClick={()=>setCity(c)}>{c}</button>)}</div><div className="offers-empty" role="status"><span className="guest-avatar"><Icon name="tag" /></span><h3>No offers published yet{city==='All destinations'?'':' in '+city}</h3><p>Confirmed packages, dates and offer terms will appear here once available.</p></div><p className="offer-footnote">Explore our properties to find a stay or venue for your occasion.</p></>}
 <Link className="guest-explore" href="/properties">Explore our properties <Icon name="arrow" /></Link>
 </div></section>;
}
