'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import Icon from './Icon';
import styles from './HomeExtras.module.css';
const photos=[{src:'/images/hotel-room.jpg',name:'Stay inspiration'},{src:'/images/hotel-lounge.jpg',name:'Spaces to unwind'},{src:'/images/wedding-table.jpg',name:'Celebration inspiration'}];
export default function HomeExtras(){
 const [active,setActive]=useState<number|null>(null);const dialog=useRef<HTMLDialogElement>(null);const touch=useRef<number|null>(null);const [showBar,setShowBar]=useState(false);
 useEffect(()=>{if(active===null)return;const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;dialog.current?.showModal();document.body.style.overflow='hidden';return()=>{dialog.current?.close();document.body.style.overflow=overflow;previous?.focus();};},[active===null]);
 useEffect(()=>{const hero=document.querySelector('main>section');if(!hero)return;const observer=new IntersectionObserver(([entry])=>setShowBar(!entry.isIntersecting));observer.observe(hero);return()=>observer.disconnect();},[]);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');if(!('IntersectionObserver' in window))return;const animations:Animation[]=[];const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){if(!media.matches)animations.push(entry.target.animate([{opacity:.65,transform:'translateY(16px)'},{opacity:1,transform:'translateY(0)'}],{duration:500,easing:'ease-out'}));observer.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('main>section:not(:first-child)').forEach(el=>observer.observe(el));const changed=()=>{if(media.matches)animations.forEach(a=>a.cancel());};media.addEventListener('change',changed);return()=>{observer.disconnect();animations.forEach(a=>a.cancel());media.removeEventListener('change',changed);};},[]);
 function move(direction:number){setActive(i=>i===null?null:(i+direction+photos.length)%photos.length);}
 return <><section className={styles.section} aria-labelledby="gallery-heading"><div className={styles.heading}><h2 id="gallery-heading">Stay &amp; celebration inspiration</h2><p>Illustrative photography</p></div><div className={styles.gallery}>{photos.map((photo,i)=><button type="button" key={photo.src} onClick={()=>setActive(i)} aria-label={'Open '+photo.name+' gallery photo'}><Image src={photo.src} alt={photo.name+' (stock photograph)'} fill sizes="(max-width:600px) 88vw, 30vw"/><span>{photo.name}<Icon name="external"/></span></button>)}</div></section>
 <section className={styles.faq} aria-labelledby="faq-heading"><h2 id="faq-heading">Frequently asked questions</h2>{[
 ['Where are SNJ properties located?','SNJ Taj Grand, SNJ Gold Garden and SNJ Pearls Garden are in Agra. SNJ Laxmi Dham is in Vrindavan.'],
 ['Which properties offer hotel stays?','Explore SNJ Taj Grand in Agra and SNJ Laxmi Dham in Vrindavan for hotel stays.'],
 ['Can I plan a wedding or family event?','Yes. The event planner lets you prepare a draft with your venue, occasion, date and expected guests. It does not submit an enquiry or confirm a reservation.'],
 ['Can I book and pay online now?','Online reservations and payments are not live yet. The booking bar helps you prepare your stay details and explore a property.'],
 ['Where can I confirm check-in times and facilities?','Use the Contact & support page for guidance. For an existing reservation, refer to the property contact details on your booking confirmation.']
 ].map(([q,a])=><details key={q} name="home-faq"><summary>{q}<Icon name="chevron"/></summary><p>{a}</p></details>)}<Link href="/contact">More help <Icon name="arrow"/></Link></section>
 <dialog ref={dialog} className={styles.lightbox} aria-label="Inspiration photo gallery" onCancel={()=>setActive(null)} onClick={e=>{if(e.target===e.currentTarget)setActive(null);}} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();move(1);}if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}}}>{active!==null&&<div className={styles.viewer}><div className={styles.toolbar}><div><strong>{photos[active].name}</strong><small>Illustrative photography &middot; {active+1} / {photos.length}</small></div><button autoFocus type="button" aria-label="Close gallery" onClick={()=>setActive(null)}><Icon name="close"/></button></div><div className={styles.large} onTouchStart={e=>{touch.current=e.touches[0].clientX;}} onTouchCancel={()=>{touch.current=null;}} onTouchEnd={e=>{if(touch.current!==null){const delta=e.changedTouches[0].clientX-touch.current;if(Math.abs(delta)>50)move(delta<0?1:-1);}touch.current=null;}}><Image src={photos[active].src} alt={photos[active].name+' (stock photograph)'} fill sizes="90vw"/><button type="button" aria-label="Previous gallery photo" onClick={()=>move(-1)}><span>&larr;</span></button><button type="button" aria-label="Next gallery photo" onClick={()=>move(1)}><span>&rarr;</span></button></div><div className={styles.thumbnails}>{photos.map((p,i)=><button type="button" key={p.src} aria-label={'Show '+p.name} aria-pressed={active===i} onClick={()=>setActive(i)}><Image src={p.src} alt="" width={80} height={55}/></button>)}</div></div>}</dialog>
 {showBar&&<nav className={styles.mobileBar} aria-label="Quick booking"><Link href="/book">Book a stay <Icon name="bed"/></Link><Link href="/weddings-events">Plan an event <Icon name="calendar"/></Link></nav>}
 </>;
}
