'use client';
import {useEffect,useId,useRef,useState} from 'react';
import Icon from './Icon';
import styles from './BookingPicker.module.css';
type Choice={slug:string;name:string;city:string};
type Props={label:string;kind:'property'|'date'|'guests'|'range'|'party';value:string;onChange:(value:string)=>void;choices?:Choice[];min?:string;max?:number;rangeStart?:string;openSignal?:number};
const iso=(d:Date)=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const parse=(v:string)=>new Date(v+'T12:00:00');
const pretty=(v:string)=>v?parse(v).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'Select date';
export default function BookingPicker({label,kind,value,onChange,choices=[],min,max=30,rangeStart,openSignal=0}:Props){
 const [range,setRange]=useState<string[]>(['','']);const [phase,setPhase]=useState<'in'|'out'>('in');const [party,setParty]=useState({rooms:1,adults:2,children:0});
 const [open,setOpen]=useState(false);const [month,setMonth]=useState('');const [draft,setDraft]=useState(value);const [position,setPosition]=useState({left:16,top:100});
 const trigger=useRef<HTMLButtonElement>(null);const dialog=useRef<HTMLDialogElement>(null);const id=useId();
 const today=iso(new Date());const earliest=min&&min>today?min:today;
 function show(){setDraft(value);const start=kind==='range'?value.split('|')[0]:value;if(kind==='range'){setRange(value.split('|'));setPhase('in');}if(kind==='party')setParty(JSON.parse(value));setMonth((start&&/^\d{4}-\d{2}-\d{2}$/.test(start)&&start>=earliest?start:earliest).slice(0,7));setOpen(true);}
 const signal=useRef(openSignal);useEffect(()=>{if(signal.current!==openSignal){signal.current=openSignal;if(openSignal)show();}},[openSignal]);
 useEffect(()=>{if(!open)return;const anchor=trigger.current;const previous=document.body.style.overflow;const place=()=>{const rect=anchor!.getBoundingClientRect();const height=dialog.current?.offsetHeight||390;setPosition({left:Math.max(12,Math.min(rect.left,window.innerWidth-352)),top:Math.max(12,Math.min(rect.bottom+12,window.innerHeight-height-12))});};dialog.current?.showModal();place();document.body.style.overflow='hidden';window.addEventListener('resize',place);return()=>{dialog.current?.close();document.body.style.overflow=previous;window.removeEventListener('resize',place);anchor?.focus();};},[open]);
 function select(next:string){setOpen(false);requestAnimationFrame(()=>onChange(next));}
 const property=choices.find(p=>p.slug===value);const committed=kind==='party'?JSON.parse(value):null;const dates=value.split('|');const nights=range[0]&&range[1]?Math.round((Date.parse(range[1])-Date.parse(range[0]))/86400000):0;const caption=kind==='range'?(dates[0]&&dates[1]?pretty(dates[0])+' - '+pretty(dates[1]):'Check-in - Check-out'):kind==='party'?committed.rooms+' room'+(committed.rooms===1?'':'s')+', '+committed.adults+' adults, '+committed.children+' children':kind==='date'?pretty(value):kind==='guests'?value+' guests':property?.name||'Select property';
 const first=month?parse(month+'-01'):new Date();const days=new Date(first.getFullYear(),first.getMonth()+1,0).getDate();const offset=(first.getDay()+6)%7;
 function shift(amount:number){setMonth(iso(new Date(first.getFullYear(),first.getMonth()+amount,1)).slice(0,7));}
 return <><button ref={trigger} type="button" className={styles.trigger} aria-label={label+': '+caption} aria-haspopup="dialog" aria-expanded={open} aria-controls={id} onClick={show}><span className={styles.leading}><Icon name={(kind==='date'||kind==='range')?'calendar':(kind==='guests'||kind==='party')?'user':'bed'}/></span><span className={styles.text}><span className={styles.label}>{label}</span><strong data-empty={kind==='date'&&!value}>{caption}</strong>{kind==='range'&&dates[0]&&dates[1]&&<small>{Math.round((Date.parse(dates[1])-Date.parse(dates[0]))/86400000)} nights</small>}{kind==='property'&&<small>{property?.city}</small>}</span><Icon name="chevron"/></button>
 <dialog ref={dialog} id={id} className={styles.popup} style={{left:position.left,top:position.top}} aria-labelledby={id+'-title'} onCancel={()=>setOpen(false)} onClick={e=>{if(e.target===e.currentTarget)setOpen(false);}}><div className={styles.inner}>
 <div className={styles.top}><h3 id={id+'-title'}>{kind==='property'?'Choose your '+label.toLowerCase():kind==='range'?'Choose your stay dates':kind==='date'?'Choose '+label.toLowerCase():'Who is joining?'}</h3><button type="button" aria-label="Close picker" onClick={()=>setOpen(false)}><Icon name="close"/></button></div>
 {open&&kind==='property'&&<div className={styles.options}>{choices.map(p=><button type="button" key={p.slug} aria-pressed={p.slug===value} onClick={()=>select(p.slug)}><span><strong>{p.name}</strong><small><Icon name="pin"/>{p.city}</small></span><span className={styles.radio}/></button>)}</div>}
 {open&&(kind==='date'||kind==='range')&&<>{kind==='range'&&<div className={styles.rangeTabs}><button type="button" aria-pressed={phase==='in'} onClick={()=>setPhase('in')}>Check-in<small>{pretty(range[0])}</small></button><button type="button" aria-pressed={phase==='out'} disabled={!range[0]} onClick={()=>setPhase('out')}>Check-out<small>{pretty(range[1])}</small></button></div>}<div className={styles.month}><button type="button" aria-label="Previous month" disabled={month<=earliest.slice(0,7)} onClick={()=>shift(-1)}><span aria-hidden="true">&larr;</span></button><strong aria-live="polite">{first.toLocaleDateString('en-GB',{month:'long',year:'numeric'})}</strong><button type="button" aria-label="Next month" onClick={()=>shift(1)}><span aria-hidden="true">&rarr;</span></button></div><div className={styles.week} aria-hidden="true">{['Mo','Tu','We','Th','Fr','Sa','Su'].map(d=><span key={d}>{d}</span>)}</div><div className={styles.calendar} role="group" aria-label="Available dates">{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0');return <button type="button" key={date} disabled={date<earliest||(kind==='range'&&phase==='out'&&date<=range[0])} aria-label={pretty(date)} aria-pressed={kind==='range'?range.includes(date):date===value} aria-current={date===today?'date':undefined} data-range={kind==='range'?!!range[0]&&!!range[1]&&date>range[0]&&date<range[1]:!!rangeStart&&date>rangeStart&&date<value} onClick={()=>{if(kind!=='range'){select(date);return;}if(phase==='in'){setRange([date,'']);setPhase('out');}else{setRange([range[0],date]);}}}>{i+1}</button>;})}</div><div className={styles.calendarFoot}>{kind==='range'?(nights>0?nights+' night'+(nights===1?'':'s')+' selected':phase==='in'?'Choose your check-in date.':'Now choose your check-out date.'):rangeStart?'Check-in: '+pretty(rangeStart):'Choose a date for your visit.'}</div>{kind==='range'&&<button type="button" className={styles.done} disabled={nights<=0} onClick={()=>select(range.join('|'))}>Continue to guests <Icon name="arrow"/></button>}</>}
 {open&&kind==='guests'&&<><div className={styles.stepper}><div><strong>Guests</strong><small>Total people attending</small></div><button type="button" aria-label="Remove guest" disabled={Number(draft)<=1} onClick={()=>setDraft(String(Math.max(1,Number(draft)-1)))}>&minus;</button><input aria-label="Number of guests" type="number" min="1" max={max} value={draft} onChange={e=>setDraft(e.target.value)}/><button type="button" aria-label="Add guest" disabled={Number(draft)>=max} onClick={()=>setDraft(String(Math.min(max,Number(draft)+1)))}>+</button></div><p className={styles.hint}>Between 1 and {max.toLocaleString('en-IN')} guests</p><button className={styles.done} type="button" disabled={!Number.isInteger(Number(draft))||Number(draft)<1||Number(draft)>max} onClick={()=>select(String(Number(draft)))}>Apply guests <Icon name="arrow"/></button></>}
 {open&&kind==='party'&&<>{(['rooms','adults','children'] as const).map(key=><div className={styles.stepper} key={key}><div><strong>{key[0].toUpperCase()+key.slice(1)}</strong></div><button type="button" aria-label={'Remove '+key} disabled={party[key]<=(key==='children'?0:key==='adults'?party.rooms:1)} onClick={()=>setParty({...party,[key]:party[key]-1})}>&minus;</button><output aria-label={key+' count'}>{party[key]}</output><button type="button" aria-label={'Add '+key} disabled={party[key]>=(key==='rooms'?10:30)} onClick={()=>setParty({...party,[key]:party[key]+1,...(key==='rooms'?{adults:Math.max(party.adults,party.rooms+1)}:{})})}>+</button></div>)}<p className={styles.hint}>At least one adult per room. Final occupancy is subject to hotel confirmation.</p><button type="button" className={styles.done} onClick={()=>select(JSON.stringify(party))}>Apply guests <Icon name="arrow"/></button></>}
 </div></dialog></>;
}
