'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import Icon from './Icon';
import styles from './HomeExtras.module.css';
import propertyStyles from './PropertyExperience.module.css';
export default function PropertyGallery({photos:items,hotel}:{photos:string[][];hotel:boolean}){
 const photos=items.map(([file,name])=>({src:'/images/'+file,name}));
 const [active,setActive]=useState<number|null>(null);const dialog=useRef<HTMLDialogElement>(null);const touch=useRef<number|null>(null);const isOpen=active!==null;
 useEffect(()=>{if(!isOpen)return;const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;dialog.current?.showModal();document.body.style.overflow='hidden';return()=>{dialog.current?.close();document.body.style.overflow=overflow;previous?.focus();};},[isOpen]);
 function move(direction:number){setActive(i=>i===null?null:(i+direction+photos.length)%photos.length);}
 return <><section className={propertyStyles.gallery} data-hotel={hotel} aria-label="Property photo gallery">{photos.map((p,i)=><button key={p.src} onClick={()=>setActive(i)} aria-label={'Open '+p.name+' photos'}><Image src={p.src} alt={p.name+' (stock photograph)'} fill sizes="(max-width:700px) 90vw, 60vw" priority={i===0}/><span>{p.name}<Icon name="external"/></span></button>)}</section> <dialog ref={dialog} className={styles.lightbox} aria-label="Inspiration photo gallery" onCancel={()=>setActive(null)} onClick={e=>{if(e.target===e.currentTarget)setActive(null);}} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();move(1);}if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}}}>{active!==null&&<div className={styles.viewer}><div className={styles.toolbar}><div><strong>{photos[active].name}</strong><small>{active+1} / {photos.length}</small></div><button autoFocus type="button" aria-label="Close gallery" onClick={()=>setActive(null)}><Icon name="close"/></button></div><div className={styles.large} onTouchStart={e=>{touch.current=e.touches[0].clientX;}} onTouchCancel={()=>{touch.current=null;}} onTouchEnd={e=>{if(touch.current!==null){const delta=e.changedTouches[0].clientX-touch.current;if(Math.abs(delta)>50)move(delta<0?1:-1);}touch.current=null;}}><Image src={photos[active].src} alt={photos[active].name+' (stock photograph)'} fill sizes="90vw"/><button type="button" aria-label="Previous gallery photo" onClick={()=>move(-1)}><span>&larr;</span></button><button type="button" aria-label="Next gallery photo" onClick={()=>move(1)}><span>&rarr;</span></button></div><div className={styles.thumbnails}>{photos.map((p,i)=><button type="button" key={p.src} aria-label={'Show '+p.name} aria-pressed={active===i} onClick={()=>setActive(i)}><Image src={p.src} alt="" width={80} height={55}/></button>)}</div></div>}</dialog></>;
}
